package drippyspelunk.controller.input;

import drippyspelunk.controller.core.StateManager;

import java.awt.event.KeyEvent;

/**
 * The controller for the game over screen.
 * This class handles user input, specifically key presses,
 * to transition from the game over screen back to the title screen.
 *
 * @author Devin Arroyo
 * @version 1.0
 */
public class GameOverController implements IController {

    /**
     * The StateManager instance to handle state transitions.
     */
    private final StateManager myStateManager;

    /**
     * Constructs a GameOverController.
     *
     * @param theStateManager The {@link StateManager} instance to handle state transitions.
     */
    public GameOverController(final StateManager theStateManager) {
        myStateManager = theStateManager;
    }

    @Override
    public void keyTyped(final KeyEvent theEvent) {
        // Not used
    }

    /**
     * Handles key press events.
     * Any key press will trigger a transition back to the title screen.
     *
     * @param theEvent The {@link KeyEvent} generated by the key press.
     */
    @Override
    public void keyPressed(final KeyEvent theEvent) {
        myStateManager.goToTitleScreen();
    }

    @Override
    public void keyReleased(final KeyEvent theEvent) {
        // Not used
    }

    @Override
    public void cleanup() {
        // No resources to clean up for this controller.
    }
}